language: Snakemake
name: sequana_hic
description: Hi-C analysis, snakemake, sequana, container, reproducibility
url: https://github.com/sequana/sequana_hic/blob/master/sequana_pipelines/hic/hic.rules
categories: [NGS, snakemake, sequana]
authors:
    - firstname: Thomas
      lastname: Cokelaer
      email: thomas.cokelaer@pasteur.fr

