# Schema validator for the Hi-C
# author: Thomas Cokelaer

type: map
mapping:
    "sequana_wrappers":
        type: str
        required: False
    "input_directory":
        type: str
        required: True
    "input_readtag":
        type: str
        required: False
    "input_pattern":
        type: str
        required: True
    "general":
        type: map
        mapping:
            "mapper":
                type: str
                required: True
                enum: ["bwa", "bwa_split", "chromap"]
            "reference_file":
                type: str
                required: True
    "apptainers":
        type: any
       
    "fastp":
      type: map
      mapping:
        "options":
            type: str
        "minimum_length":
            required: True
            type: int
        "adapters":
            type: str
            required: False
        "quality":
            type: int
            range: {max: 40, min: 0}
            required: False
        "threads":
            type: int
            required: True
            range: { min: 1 }
        "disable_adapter_trimming":
            type: bool
        "disable_quality_filtering":
            type: bool
        "resources":
            type: any
            required: true

    "bwa_index":
        type: map
        mapping:
            "options":
                type: str
                required: False
            "threads":
                type: int
                required: True
                range: { min: 1 }
            "resources":
                type: any
                required: True
    "bwa":
        type: map
        mapping:
            "index_algorithm":
                type: str
                required: False
            "options":
                type: str
                required: False
            "threads":
                type: int
                required: True
                range: { min: 1 }
            "tmp_directory":
                type: str
                required: False
            "resources":
                type: any
                required: True
    "bwa_split":
        type: map
        mapping:
            "nreads":
                type: int
                required: False
            "index_algorithm":
                type: str
                required: False
            "options":
                type: str
                required: False
            "threads":
                type: int
                required: True
                range: { min: 1 }
            "tmp_directory":
                type: str
                required: False
            "resources":
                type: any
                required: True
    "chromap":
        type: map
        mapping:
            "threads":
                type: int
                required: True
                range: { min: 1 }
            "resources":
                type: any
                required: True
    "fastqc":
        type: map
        mapping:
            "options":
                type: str
                required: False
            "threads":
                type: int
                required: True
                range: { min: 1 }
            "resources":
                type: any
                required: True
    "multiqc":
        type: map
        mapping:
            "options":
                type: str
                required: False
            "modules":
                type: str
                required: False
            "input_directory":
                type: str
                required: False
            "config_file":
                type: str
                required: False
            "resources":
                type: any
                required: True
    "pairtools":
        type: map
        mapping:
            "options":
                type: str
                required: False
            "walk_policy":
                type: str
                required: True
                enum: ["mask", "5any", "5unique", "3any", "3unique", "all"]
            "threads":
                type: int
                required: True
                range: { min: 1 }
            "resources":
                type: any
                required: True

